name: Run java -version in a branch
on:
  push:
    branches: [ main ]
    paths:
      - '.github/**'

jobs:
  testaction:
    name: "Run a few things ..."
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: pwd
        run: |
          pwd

      - name: Download latest JDK21
        run: |
          curl -L -o jdk.tar.gz https://api.adoptium.net/v3/binary/version/jdk-21+22-ea-beta/linux/x64/jdk/hotspot/normal/eclipse

      - name: list
        run: |
          ls -ld $PWD/*

      - uses: actions/setup-java@v3
        with:
          jdkFile: jdk.tar.gz
          java-version: '21'
          java-package: jdk
          architecture: x64
          distribution: 'jdkfile'

      - name: Run which javac
        run: |
          javac -version

      - name: Run java version
        run: |
          java -version
