name: Run java -version
on:
  push:
    branches: [ master ]
    paths:
      - '.github/**'

jobs:
  testaction:
    name: "Run a few things ..."
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          java-package: jdk
          architecture: x64
          distribution: 'temurin'


      - name: pwd
        run: |
          pwd

      - name: Run which javac
        run: |
          javac -version

      - name: Run java version
        run: |
          java -version
